### ISSUE TITLE
5-min facet fiddle wrong

### ISSUE THREAD

**Issue by JonnyFunFun** [TargetProcess/taucharts-docs#6]
The jsFiddle link on the [5-minute tutorial](https://github.com/TargetProcess/taucharts-docs/blob/df1cfebe98417ba8ae900c0b1ecb5995484157ca/tutorials/5min.md#L85) in the facet chart section is not the correct fiddle.  It is a copy of the jsFiddle previous on that same page.

**Comment by vladminsky** [comment]
Thanks! Fixed
